weave:
  image: binocarlos/powerstrip-weave
  ports:
    - "80"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: launch 192.168.99.102
powerstrip:
  image: clusterhq/powerstrip
  ports:
    - "2375"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - adapters.yml:/etc/powerstrip/adapters.yml
  links:
    - weave:weave
nginx:
  build: ./powerstrip-nginx
  ports:
    - "2376:2376"
  links:
    - powerstrip:powerstrip
  volumes:
    - /var/lib/boot2docker:/etc/ssl/certs
